name: TWRP

on:
  push:      
    branches: 
      - '**'   # This will match all branches
    paths-ignore:
      - 'README.md'
  pull_request: 
    branches: 
      - '**'   # This will match all branches
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    inputs:
      upload_releases:
        description: 'Upload releases'
        required: true
        default: 'true'
        type: boolean
      mark_prerelease:
        description: 'Mark as prerelease'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    name: Build twrp by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clean ubuntu
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
    - name: Build TWRP Recovery
      uses: mlm-games/TWRP-recovery-build-action@main 
      with:
        MANIFEST_BRANCH: 'twrp-9.0'
        DEVICE_TREE_BRANCH: 'test-decrypt'

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      if: inputs.upload_releases == false || github.event_name != 'workflow_dispatch'
      with:
        name: TWRP-Recovery-${{ github.repository }}
        path: ${{ env.OUTPUT_DIR }}/*.img

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'workflow_dispatch' && inputs.upload_releases == true
      with:
        files: |
          ${{ env.OUTPUT_DIR }}/*.img
          ${{ env.OUTPUT_DIR }}/*.tar
          ${{ env.OUTPUT_DIR }}/*vbmeta*    
          ${{ env.OUTPUT_DIR }}/ramdisk-recovery.*
        name: Unofficial ${{ github.workflow }} for ${{ env.DEVICE_NAME }} // ${{ format('{0:yyyyMMdd}', github.event.head_commit.timestamp) }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ env.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE }}/tree/${{ env.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ github.server_url }}/${{ github.repository }}/commit/$(git rev-parse --short HEAD)) during building.
          MD5 (img): ${{ env.MD5_IMG }}
          MD5 (zip): ${{ env.MD5_ZIP }}
        prerelease: ${{ inputs.mark_prerelease }}

    - name: Run LDCHECK
      uses: mlm-games/ldcheck-action@main
      with:
        OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
        LDCHECKPATH: system/bin/teei_loader
